#!/usr/bin/env node

import { spawn, execFileSync } from 'node:child_process';
import { accessSync, chmodSync, constants, existsSync, lstatSync, mkdirSync,
  readFileSync, realpathSync, renameSync, unlinkSync, writeFileSync } from 'node:fs';
import { dirname, isAbsolute, join, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const BASELINE = '5badb15009ae1756c3afe0ae0cef1faafc290ccc';
const VERSION = '0.2.1-alpha.1';
const PNPM_VERSION = '11.7.0';
const MARKER = '# Generated by mobile-preview-plugin/scripts/dev-dsh.mjs';
const PACKAGE_ENV = { ...process.env, COREPACK_ENABLE_NETWORK: '0',
  COREPACK_ENABLE_AUTO_PIN: '0', npm_config_manage_package_manager_versions: 'false' };
const HELP = `Usage: node scripts/dev-dsh.mjs web|desktop --source ABS_DSH_ROOT [--port 3081] [--build] [--prepare-only]

--build         Build DSH before starting its development runtime.
--prepare-only  Validate prerequisites and write isolated configuration, then exit.
--port          Web port only (default 3081).

Uses existing Node.js, pnpm and MPP; installs nothing automatically.
MPP_EXECUTABLE, MPP_ADB, MPP_EMULATOR and MPP_PNPM may select absolute executable paths.
MPP_DEVICE_ASSETS may select an absolute directory containing the Android capture artifacts.`;

function fail(message) { throw new Error(message); }

function options(argv) {
  if (argv.length === 1 && ['--help', '-h'].includes(argv[0])) return null;
  const mode = argv.shift();
  if (!['web', 'desktop'].includes(mode)) fail('Select web or desktop; use --help for usage.');
  const result = { mode, source: undefined, port: 3081, build: false, prepareOnly: false };
  const seen = new Set();
  while (argv.length) {
    const flag = argv.shift();
    if (seen.has(flag)) fail(`Duplicate option: ${flag}`);
    seen.add(flag);
    if (flag === '--build') result.build = true;
    else if (flag === '--prepare-only') result.prepareOnly = true;
    else if (flag === '--source' || flag === '--port') {
      const value = argv.shift();
      if (value === undefined || value.startsWith('--')) fail(`${flag} requires a value.`);
      if (flag === '--source') result.source = value;
      else {
        if (!/^\d+$/.test(value)) fail('--port must be an integer in 1..65535.');
        result.port = Number(value);
      }
    } else fail(`Unknown option: ${flag}`);
  }
  if (typeof result.source !== 'string' || !isAbsolute(result.source)) fail('--source must name an absolute DSH checkout path.');
  if (!Number.isSafeInteger(result.port) || result.port < 1 || result.port > 65535) fail('--port must be an integer in 1..65535.');
  if (mode === 'desktop' && seen.has('--port')) fail('--port is Web-only; Desktop uses an OS-assigned Host port.');
  return result;
}

function readJson(path, description) {
  try { return JSON.parse(readFileSync(path, 'utf8')); }
  catch { fail(`Cannot read ${description}; verify the selected DSH source checkout.`); }
}

function output(command, args, cwd, description) {
  try {
    return execFileSync(command, args, { cwd, encoding: 'utf8', timeout: 10_000,
      maxBuffer: 65_536, env: PACKAGE_ENV, stdio: ['ignore', 'pipe', 'pipe'] }).trim();
  } catch { fail(`${description} failed; check the installed command and selected source checkout.`); }
}

function executable(path, name) {
  if (!isAbsolute(path) || path.includes('\0')) fail(`${name} must be an absolute executable path.`);
  try {
    if (!lstatSync(path).isFile() && !lstatSync(path).isSymbolicLink()) throw new Error();
    const real = realpathSync(path);
    if (!lstatSync(real).isFile()) throw new Error();
    accessSync(real, constants.X_OK);
    return real;
  } catch { fail(`${name} is unavailable or not executable. For MPP, run cargo build --workspace --locked in ${ROOT}.`); }
}

function installedPnpm(source) {
  const path = join(source, 'apps/desktop/node_modules/pnpm/package.json');
  if (!existsSync(path)) return undefined;
  const manifest = readJson(path, 'the source-installed pnpm package');
  const entry = typeof manifest.bin === 'string' ? manifest.bin : manifest.bin?.pnpm;
  if (manifest.name !== 'pnpm' || manifest.version !== PNPM_VERSION
    || typeof entry !== 'string' || entry.length === 0 || isAbsolute(entry)) {
    fail(`The source-installed pnpm must be ${PNPM_VERSION} with a relative pnpm bin entry.`);
  }
  const directory = realpathSync(dirname(path));
  const target = resolve(directory, entry);
  if (!target.startsWith(`${directory}${sep}`)) fail('The source-installed pnpm bin must remain inside its package.');
  let real;
  try { real = realpathSync(target); accessSync(real, constants.R_OK); }
  catch { fail('The source-installed pnpm bin is unavailable; check the installed source dependencies.'); }
  if (!real.startsWith(`${directory}${sep}`) || !lstatSync(real).isFile()) {
    fail('The source-installed pnpm bin must be a file inside its package.');
  }
  return { command: process.execPath, args: [real] };
}

function prepareDirectory(path) {
  if (existsSync(path) && (!lstatSync(path).isDirectory() || lstatSync(path).isSymbolicLink())) {
    fail(`Development state must be an ordinary directory: ${path}`);
  }
  mkdirSync(path, { recursive: true, mode: 0o700 });
  chmodSync(path, 0o700);
}

function statIfPresent(path) {
  try { return lstatSync(path); }
  catch (error) { if (error.code === 'ENOENT') return undefined; throw error; }
}

function writePatch(home, config) {
  const path = join(home, 'cordis.patch.yml');
  const contents = `${MARKER}\n- insert:\n    - id: mobile-preview\n      name: ${JSON.stringify(join(ROOT, 'packages/dsh-plugin/index.js'))}\n      config:\n${Object.entries(config).map(([key, value]) => `        ${key}: ${JSON.stringify(value)}\n`).join('')}`;
  const stat = statIfPresent(path);
  if (stat !== undefined) {
    if (!stat.isFile() || stat.isSymbolicLink() || stat.size > 65_536
      || !readFileSync(path, 'utf8').startsWith(`${MARKER}\n`)) {
      fail(`Refusing to overwrite an unrecognized development patch: ${path}`);
    }
    if (readFileSync(path, 'utf8') === contents) return;
  }
  const temporary = `${path}.${process.pid}.tmp`;
  let created = false;
  try {
    writeFileSync(temporary, contents, { encoding: 'utf8', mode: 0o600, flag: 'wx' });
    created = true;
    renameSync(temporary, path);
  } finally {
    if (created && existsSync(temporary)) unlinkSync(temporary);
  }
}

async function main() {
  const settings = options(process.argv.slice(2));
  if (settings === null) { console.log(HELP); return; }
  const [major, minor] = process.versions.node.split('.').map(Number);
  if (!(major === 22 && minor >= 19) && major < 24) fail('DSH requires Node.js 22.19+ on the 22.x line, or Node.js 24+. Select an installed supported Node on PATH.');
  const manifest = readJson(join(settings.source, 'package.json'), 'the DSH root package');
  const desktop = readJson(join(settings.source, 'apps/desktop/package.json'), 'the DSH Desktop package');
  if (manifest.name !== '@deepseek-ai/dsh-root' || manifest.version !== VERSION
    || desktop.name !== '@deepseek-ai/dsh-desktop' || desktop.version !== VERSION) {
    fail(`Unsupported DSH source; this launcher targets root and Desktop ${VERSION}. It does not use the installed application.`);
  }
  const source = realpathSync(settings.source);
  const top = output('git', ['rev-parse', '--show-toplevel'], source, 'Git checkout inspection');
  const commit = output('git', ['rev-parse', 'HEAD'], source, 'Git baseline inspection');
  if (realpathSync(top) !== source || commit !== BASELINE) fail(`Unsupported DSH checkout; select repository root at commit ${BASELINE}.`);
  if (manifest.packageManager?.split('+')[0] !== `pnpm@${PNPM_VERSION}`) {
    fail(`The pinned source must declare pnpm@${PNPM_VERSION}.`);
  }
  const pnpm = process.env.MPP_PNPM !== undefined
    ? { command: executable(process.env.MPP_PNPM, 'MPP_PNPM'), args: [] }
    : installedPnpm(source) ?? { command: 'pnpm', args: [] };
  const actual = output(pnpm.command, [...pnpm.args, '--version'], source, 'pnpm version check');
  if (actual !== PNPM_VERSION) fail(`Use exactly pnpm ${PNPM_VERSION} from the installed source dependencies or select it with MPP_PNPM; other versions are unsupported.`);
  const config = {
    executable: executable(process.env.MPP_EXECUTABLE ?? join(ROOT, 'target/debug/mpp'), 'MPP_EXECUTABLE'),
    deviceAssets: process.env.MPP_DEVICE_ASSETS ?? join(ROOT, 'target/android-device'),
  };
  if (!isAbsolute(config.deviceAssets) || config.deviceAssets.includes('\0')) fail('MPP_DEVICE_ASSETS must be an absolute directory path.');
  for (const key of ['adb', 'emulator']) {
    const value = process.env[`MPP_${key.toUpperCase()}`];
    if (value !== undefined) config[key] = executable(value, `MPP_${key.toUpperCase()}`);
  }
  if (!existsSync(join(ROOT, 'packages/dsh-plugin/index.js'))) fail('The local MPP DSH plugin entry is missing.');
  const picker = join(source, 'apps/web/tests/pin-browse-picker.overlay.yml');
  if (settings.mode === 'web' && !existsSync(picker)) fail('The pinned DSH browser-picker overlay is missing.');
  const state = join(ROOT, 'target/dsh');
  prepareDirectory(state);
  const home = join(state, `${settings.mode}-home`);
  prepareDirectory(home);
  writePatch(home, config);
  const environment = { ...PACKAGE_ENV, DSH_HOME: home };
  let args;
  if (settings.mode === 'web') {
    args = ['run', 'dev:web', ...(settings.build ? [] : ['--skip-build']),
      '--patch', picker, '--no-open', '--port', String(settings.port)];
  } else {
    const userData = join(state, 'desktop-user-data');
    prepareDirectory(userData);
    Object.assign(environment, { DSH_DESKTOP_USER_DATA_DIR: userData,
      DSH_DESKTOP_MAIN_INSPECT_PORT: process.env.DSH_DESKTOP_MAIN_INSPECT_PORT ?? '9239',
      DSH_DESKTOP_RENDERER_DEBUG_PORT: process.env.DSH_DESKTOP_RENDERER_DEBUG_PORT ?? '9232',
      DSH_DESKTOP_HOST_INSPECT_PORT: process.env.DSH_DESKTOP_HOST_INSPECT_PORT ?? '9240',
      DSH_DESKTOP_OPEN_DEVTOOLS: process.env.DSH_DESKTOP_OPEN_DEVTOOLS ?? '0' });
    args = ['run', settings.build ? 'dev:desktop' : 'start:desktop'];
  }
  console.log(`MPP ${settings.mode} development: DSH ${VERSION} (${BASELINE.slice(0, 7)}); isolated state ${home}`);
  if (settings.prepareOnly) { console.log('Configuration prepared; no DSH process was started.'); return; }
  const child = spawn(pnpm.command, [...pnpm.args, ...args], { cwd: source, env: environment, stdio: 'inherit', shell: false });
  const forward = signal => { if (child.exitCode === null && child.signalCode === null) child.kill(signal); };
  const onInt = () => forward('SIGINT');
  const onTerm = () => forward('SIGTERM');
  process.on('SIGINT', onInt);
  process.on('SIGTERM', onTerm);
  try {
    process.exitCode = await new Promise((accept, reject) => {
      child.once('error', () => reject(new Error('Could not start the installed pnpm executable.')));
      child.once('exit', (code, signal) => accept(code ?? (signal === 'SIGINT' ? 130 : signal === 'SIGTERM' ? 143 : 1)));
    });
  } finally {
    process.off('SIGINT', onInt);
    process.off('SIGTERM', onTerm);
  }
}

main().catch(error => { console.error(`dev-dsh: ${error.message}`); process.exitCode = 1; });
