[package]
name = "mpp-host"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[[bin]]
name = "mpp"
path = "src/main.rs"

[dependencies]
mpp-core.workspace = true
mpp-android.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true

[lints]
workspace = true
